#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority filter; policy drop;

    # Allow established and related traffic
    ct state established,related accept comment "Allow return traffic"

    # Drop invalid connections
    ct state invalid drop comment "Early drop of invalid connections"

    # Allow loopback
    iifname "lo" accept comment "Allow from loopback"

    # Allow ICMP (Ping)
    icmp type echo-request accept comment "Allow IPv4 ping"
    icmpv6 type { echo-request, nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert } accept comment "Allow IPv6 essentials"

    # Services
    tcp dport 49152 accept comment "Allow SSH"

    # --- Add rootless service ports below ---
    # tcp dport { 80, 443 } accept comment "Example: Web Services"

    # Log and reject everything else
    # limit rate 5/minute log prefix "nft-input-reject: "
    reject with icmpx type admin-prohibited
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}
